#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
---
version: "3.7"
services:
  tailscale-home:
    image: tailscale/tailscale:latest
    hostname: tailscale-home
    environment:
      - TS_AUTHKEY=tskey-client-kzDYs1eHAm11CNTRL-TqYSiGtnqnCkkvG3pnbHnCerbaTmRDhb?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - '7575:7575'
    cap_add:
      - net_admin
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=2f54502898b89a1757ac61e13a944b7bbc3b97f4d66a5a21dba16ac4160b98b9
    depends_on:
      - tailscale-home
    network_mode: service:tailscale-home		
